### ISSUE TITLE
Multi instances of node are not supported by function

### ISSUE THREAD

**Issue by lewang0418** [aria-tosca/aria-examples#16]
Hi,

In ARIA, the way to run fabric is to include the following information as inputs
 
`implementation: fabric.fabric_plugin.tasks.run_script
       inputs:
            script_path:
              default: scripts/bind9/start.sh
            fabric_env:
              default:
                host_string: { get_attribute: [ dns_vm_ip, floating_ip_address ] }
                user: { get_input: agent_user }
                key_filename: { get_input: local_path }
`

When creating multi instances of a node, the Intrinsic function "get_attribute" would find multiple nodes named "dns_vm_ip" causing "Unable to evaluate get_attribute function: Multi instances of node are not supported by function" error. How do you solve this problem?

BR,
Le

**Comment by denismakogon** [comment]
Hello @lewang0418 would you mind to provide a blueprint so i can answer your question more wisely.

**Comment by lewang0418** [comment]
I am implementing scaling in ARIA-TOSCA, which is not implemented currently. I am now able to scale up a node, for example, scaling bind9 node in bind9-dns-multicloud-blueprint.yaml. 

After scaling-up, there is a new VM created for bind9_host. The problem I encounter is this "Unable to evaluate get_attribute function: Multi instances of node are not supported by function" when fabric plugin tries to login to this newly created host. 

I think the problem occurs when create/install workflows are called, but fabric finds out there are two hosts (existing and newly created VMs) having exactly the same credential(username). So fabric seems confused by these same credentials. 

What I am looking for here is tips to overcome this issue. Thanks.

BR,
Le

**Comment by denismakogon** [comment]
IIRC, Aria does not support scaling. You may need to refer this question to Cloudify team regarding Fabric plugin.

**Comment by lewang0418** [comment]
Thanks, I will refer this to Cloudify team.
